# Generated by Django 5.2.4 on 2025-07-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ec_products', '0002_auto_20250215_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ec_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='ec_products.ec_product')),
            ],
        ),
    ]
