# Generated by Django 3.2.12 on 2025-02-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec_checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ec_order',
            options={'verbose_name_plural': 'EC_Orders'},
        ),
        migrations.RenameField(
            model_name='ec_orderlineitem',
            old_name='product',
            new_name='ec_product',
        ),
        migrations.RenameField(
            model_name='ec_orderlineitem',
            old_name='product_size',
            new_name='ec_product_size',
        ),
    ]
