# Generated by Django 3.2.12 on 2025-02-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_checkout', '0002_auto_20250216_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec_order',
            name='original_ec_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ec_order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
