# Generated by Django 3.2.12 on 2025-02-19 13:05

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ec_checkout', '0003_auto_20250218_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec_order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
