# Generated by Django 3.2.12 on 2025-02-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ec_profiles', '0001_initial'),
        ('ec_checkout', '0004_alter_ec_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec_order',
            name='ec_user_profile',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ec_orders',
                to='ec_profiles.ec_userprofile'),
        ),
    ]
