# Generated by Django 3.2.12 on 2025-02-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ec_category',
            options={'verbose_name_plural': 'EC_Categories'},
        ),
        migrations.AlterModelOptions(
            name='ec_product',
            options={'verbose_name_plural': 'EC_Products'},
        ),
        migrations.AddField(
            model_name='ec_product',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
